vich_uploader:
    db_driver: orm

    mappings:
       trick_images:
           uri_prefix: /pictures/contributions
           upload_destination: '%kernel.project_dir%/public/pictures/contributions'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
